# Generated by Django 5.2 on 2025-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='titre',
            field=models.CharField(default='New chat', max_length=50),
        ),
    ]
